#include "ui/full_catalog_screen.hpp"
#include "diagnostic_logger.hpp"

#include <psp2/ctrl.h>
#include <psp2/kernel/clib.h>
#include <psp2/kernel/processmgr.h>

#include <algorithm>
#include <cctype>
#include <cstring>
#include <utility>

namespace psvitaalive::ui {
namespace {
constexpr unsigned BG = RGBA8(0,0,0,255);
constexpr unsigned SURFACE = RGBA8(0x37,0x37,0x37,255);
constexpr unsigned SURFACE2 = RGBA8(0x2A,0x2A,0x2A,255);
constexpr unsigned BORDER = RGBA8(0x6E,0x6E,0x6E,255);
constexpr unsigned TEXT = RGBA8(0xAA,0xAA,0xAA,255);
constexpr unsigned DIM = RGBA8(0x6E,0x6E,0x6E,255);
constexpr unsigned ACCENT = RGBA8(0x3B,0xFF,0,255);
constexpr unsigned WHITE = RGBA8(255,255,255,255);
constexpr unsigned PANEL = RGBA8(0x20,0x20,0x20,255);
constexpr int FULL_CARD_H=120, SPLIT_CARD_H=82, DETAIL_HEADER_H=92, LINE_H=18, TRANSITION_MS=200;
constexpr int LINK_ROW_H=38, LINK_GAP=6, SCREENSHOT_ROW_H=86;
// Keep the number of decoded GPU textures intentionally small. vita2d textures
// are uncompressed in memory, so a large cache can exhaust Vita/GXM memory even
// when the source PNG/JPEG files are small on disk.
constexpr size_t MAX_APP_TEXTURES=9;
constexpr size_t MAX_SCREENSHOT_TEXTURES=3;
constexpr uint64_t DIRECTION_REPEAT_DELAY_US=250000;
constexpr uint64_t DIRECTION_REPEAT_INTERVAL_US=70000;

const char* extOf(const std::string& p){const size_t dot=p.find_last_of('.');return dot==std::string::npos?"":p.c_str()+dot;}
std::string formatBytes(uint64_t bytes){const double b=static_cast<double>(bytes);char out[64];if(bytes>=1024ULL*1024ULL*1024ULL)sceClibSnprintf(out,sizeof(out),"%.2f GB",b/(1024.0*1024.0*1024.0));else if(bytes>=1024ULL*1024ULL)sceClibSnprintf(out,sizeof(out),"%.2f MB",b/(1024.0*1024.0));else if(bytes>=1024ULL)sceClibSnprintf(out,sizeof(out),"%.2f KB",b/1024.0);else sceClibSnprintf(out,sizeof(out),"%llu B",static_cast<unsigned long long>(bytes));return out;}
std::string lowerAscii(std::string s){for(char&c:s)c=(char)std::tolower((unsigned char)c);return s;}
std::string ellipsize(const std::string& s,size_t maxChars){if(s.size()<=maxChars)return s;if(maxChars<=3)return s.substr(0,maxChars);return s.substr(0,maxChars-3)+"...";}
bool actionableLink(const CatalogLink& l){const std::string t=lowerAscii(l.type);if(t=="download"||t=="downloads"||t=="mirror"||t=="dlc")return true;const std::string u=lowerAscii(l.url);return u.find(".vpk")!=std::string::npos||u.find(".pkg")!=std::string::npos||u.find(".zip")!=std::string::npos||u.find(".pbp")!=std::string::npos||u.find(".iso")!=std::string::npos||u.find(".cso")!=std::string::npos;}
}

FullCatalogScreen::FullCatalogScreen()=default;
FullCatalogScreen::~FullCatalogScreen(){shutdown();}
void FullCatalogScreen::setInstallCallbacks(InstallRequestFn r,InstallStatusFn s){installRequest_=std::move(r);installStatusText_=std::move(s);}
void FullCatalogScreen::setCatalogChangeCallback(CatalogChangeFn c){catalogChange_=std::move(c);}
void FullCatalogScreen::setSearchCallback(SearchRequestFn c){searchRequest_=std::move(c);}
void FullCatalogScreen::setLinkActionCallback(LinkActionFn c){linkAction_=std::move(c);}
void FullCatalogScreen::setImageCache(ImageCache* c){imageCache_=c;}
void FullCatalogScreen::setCatalogItems(std::vector<CatalogItem> items){releaseTextures();if(imageCache_)imageCache_->cancelQueuedRequests();allItems_=std::move(items);sortItemsByDate(allItems_);applySearch(searchQuery_);catalogLoading_=false;catalogError_.clear();}
void FullCatalogScreen::setActiveCatalog(CatalogType catalog){releaseTextures();if(imageCache_)imageCache_->cancelQueuedRequests();state_.catalog=catalog;searchQuery_.clear();items_=allItems_;state_.focusIndex=0;state_.catalogScrollRow=0;state_.detailScroll=0;state_.linkFocus=-1;state_.linkNavigation=false;}
void FullCatalogScreen::setCatalogLoading(bool loading,const std::string& label,uint64_t current,uint64_t total,const std::string& message){catalogLoading_=loading;catalogLoadingLabel_=label;catalogLoadingCurrent_=current;catalogLoadingTotal_=total;catalogLoadingMessage_=message;if(loading)catalogError_.clear();}
void FullCatalogScreen::setCatalogError(const std::string& e){catalogLoading_=false;catalogError_=e;}
void FullCatalogScreen::setInstallProgress(bool active,uint64_t current,uint64_t total,uint64_t bytesPerSecond,const std::string& stage,const std::string& fileName,const std::string& message){installProgressActive_=active;installProgressCurrent_=current;installProgressTotal_=total;installProgressSpeed_=bytesPerSecond;installProgressStage_=stage;installProgressFile_=fileName;installProgressMessage_=message;}

bool FullCatalogScreen::init(){vita2d_init();vita2d_set_clear_color(BG);font_=vita2d_load_default_pgf();if(!font_)return false;sceCtrlSetSamplingMode(SCE_CTRL_MODE_ANALOG);state_=UiState{};ready_=true;diagnostics::log("[UI] initialized");return true;}
void FullCatalogScreen::releaseTextures(){for(auto& e:textures_)if(e.second)vita2d_free_texture(e.second);textures_.clear();textureOrder_.clear();}
void FullCatalogScreen::touchTexture(const std::string& path){auto it=std::find(textureOrder_.begin(),textureOrder_.end(),path);if(it!=textureOrder_.end())textureOrder_.erase(it);textureOrder_.push_back(path);}
void FullCatalogScreen::evictTextureIfNeeded(const std::string& ns){const size_t limit=ns=="shot"?MAX_SCREENSHOT_TEXTURES:MAX_APP_TEXTURES;size_t count=0;for(const auto& p:textureOrder_)if(p.find("/"+ns+"_")!=std::string::npos)++count;if(count<limit)return;for(auto it=textureOrder_.begin();it!=textureOrder_.end();++it){if(it->find("/"+ns+"_")==std::string::npos)continue;auto tex=textures_.find(*it);if(tex!=textures_.end()){if(tex->second)vita2d_free_texture(tex->second);textures_.erase(tex);}textureOrder_.erase(it);return;}}
void FullCatalogScreen::shutdown(){releaseTextures();if(font_){vita2d_free_pgf(font_);font_=nullptr;}if(ready_){vita2d_fini();ready_=false;}diagnostics::log("[UI] shutdown");}

int FullCatalogScreen::totalRows()const{return items_.empty()?0:(static_cast<int>(items_.size())+2)/3;}
int FullCatalogScreen::visibleRowsFull()const{return 3;}
int FullCatalogScreen::visibleRowsSplit()const{return std::max(1,(SCREEN_H-HEADER_H-TABS_H-FOOTER_H-GRID_PAD*2)/(SPLIT_CARD_H+CARD_GAP));}
int FullCatalogScreen::selectedIndex()const{return items_.empty()?-1:std::max(0,std::min(state_.focusIndex,(int)items_.size()-1));}
void FullCatalogScreen::clampCatalogFocus(){if(items_.empty())state_.focusIndex=0;else state_.focusIndex=std::max(0,std::min(state_.focusIndex,(int)items_.size()-1));}
void FullCatalogScreen::clampCatalogScroll(){if(items_.empty()){state_.catalogScrollRow=0;return;}const int vis=state_.mode==UiMode::FULL_CATALOG?visibleRowsFull():visibleRowsSplit();if(state_.mode==UiMode::FULL_CATALOG){int row=state_.focusIndex/3;if(row<state_.catalogScrollRow)state_.catalogScrollRow=row;if(row>=state_.catalogScrollRow+vis)state_.catalogScrollRow=row-vis+1;state_.catalogScrollRow=std::max(0,std::min(state_.catalogScrollRow,std::max(0,totalRows()-vis)));}else{int maxs=std::max(0,(int)items_.size()-vis);if(state_.focusIndex<state_.catalogScrollRow)state_.catalogScrollRow=state_.focusIndex;if(state_.focusIndex>=state_.catalogScrollRow+vis)state_.catalogScrollRow=state_.focusIndex-vis+1;state_.catalogScrollRow=std::max(0,std::min(state_.catalogScrollRow,maxs));}}

void FullCatalogScreen::sortItemsByDate(std::vector<CatalogItem>& items)const{std::stable_sort(items.begin(),items.end(),[](const CatalogItem&a,const CatalogItem&b){if(a.versionDate!=b.versionDate)return a.versionDate>b.versionDate;return lowerAscii(a.name)<lowerAscii(b.name);});}
bool FullCatalogScreen::matchesSearch(const CatalogItem&item,const std::string&query)const{if(query.empty())return true;const std::string q=lowerAscii(query);const std::string hay=lowerAscii(item.name+"\n"+item.titleId+"\n"+item.author+"\n"+item.description+"\n"+item.longDescription+"\n"+item.category+"\n"+item.subcategory);return hay.find(q)!=std::string::npos;}
void FullCatalogScreen::applySearch(const std::string&query){searchQuery_=query;items_.clear();for(const auto&item:allItems_)if(matchesSearch(item,query))items_.push_back(item);state_.focusIndex=0;state_.catalogScrollRow=0;state_.detailScroll=0;state_.linkFocus=-1;state_.linkNavigation=false;char m[256];sceClibSnprintf(m,sizeof(m),"[UI] search query='%s' results=%u",searchQuery_.c_str(),(unsigned)items_.size());diagnostics::log(m);}

int FullCatalogScreen::detailContentHeight(const CatalogItem&it,int w)const{const int cw=std::max(1,w-36),maxChars=std::max(18,cw/7);std::vector<std::string>pre,post;auto add=[&](std::vector<std::string>&lines,const char*t,const std::string&v){if(v.empty())return;lines.push_back(t);std::vector<std::string>q;wrapText(v,maxChars,q);for(auto&s:q)lines.push_back(s);lines.push_back("");};add(pre,"Description",it.description);add(pre,"Long Description",it.longDescription);add(post,"Requirements",it.requirements);post.push_back("Information");post.push_back("Title ID: "+it.titleId);post.push_back("Version: "+it.version);post.push_back("Release date: "+it.versionDate);post.push_back("Category: "+it.category);post.push_back("Subcategory: "+it.subcategory);post.push_back("Size: "+it.size);post.push_back("Status: "+it.status);post.push_back("");add(post,"Changelog",it.changelog);const int linksH=it.linkDetails.empty()?0:10+(int)it.linkDetails.size()*(LINK_ROW_H+LINK_GAP);const int screenshotRows=(std::min(5,(int)it.screenshots.size())+2)/3;return linksH+((int)pre.size()+(int)post.size())*LINE_H+screenshotRows*SCREENSHOT_ROW_H+24;}
void FullCatalogScreen::clampDetailScroll(){const int i=selectedIndex();if(i<0){state_.detailScroll=0;return;}const int visibleHeight=std::max(1,SCREEN_H-HEADER_H-TABS_H-FOOTER_H-DETAIL_HEADER_H-18);const int total=detailContentHeight(items_[i],SCREEN_W/2);state_.detailScroll=std::max(0,std::min(state_.detailScroll,std::max(0,total-visibleHeight)));if(items_[i].linkDetails.empty()){state_.linkFocus=-1;state_.linkNavigation=false;}else if(state_.linkFocus>=(int)items_[i].linkDetails.size())state_.linkFocus=(int)items_[i].linkDetails.size()-1;}

void FullCatalogScreen::moveCatalogFocus(int d){if(items_.empty())return;if(state_.mode==UiMode::FULL_CATALOG){if(d<0&&state_.focusIndex>=3)state_.focusIndex-=3;if(d>0&&state_.focusIndex+3<(int)items_.size())state_.focusIndex+=3;}else{if(d<0&&state_.focusIndex>0)--state_.focusIndex;if(d>0&&state_.focusIndex+1<(int)items_.size())++state_.focusIndex;}clampCatalogFocus();clampCatalogScroll();state_.detailScroll=0;state_.linkFocus=-1;state_.linkNavigation=false;}
void FullCatalogScreen::moveDetailScroll(int d){state_.detailScroll+=d<0?-24:24;clampDetailScroll();}
void FullCatalogScreen::moveLinkFocus(int dx,int dy){(void)dx;const int i=selectedIndex();if(i<0||items_[i].linkDetails.empty())return;const int count=(int)items_[i].linkDetails.size();if(state_.linkFocus<0)state_.linkFocus=0;else state_.linkFocus=std::max(0,std::min(count-1,state_.linkFocus+dy));state_.linkNavigation=true;const int rowTop=DETAIL_HEADER_H+10+state_.linkFocus*(LINK_ROW_H+LINK_GAP);const int visible=SCREEN_H-HEADER_H-TABS_H-FOOTER_H-DETAIL_HEADER_H-18;if(rowTop<state_.detailScroll)state_.detailScroll=rowTop;if(rowTop+LINK_ROW_H>state_.detailScroll+visible)state_.detailScroll=rowTop+LINK_ROW_H-visible;clampDetailScroll();}
void FullCatalogScreen::activateFocusedLink(){const int i=selectedIndex();if(i<0||state_.linkFocus<0||state_.linkFocus>=(int)items_[i].linkDetails.size())return;const CatalogLink&link=items_[i].linkDetails[state_.linkFocus];if(!linkAction_||!actionableLink(link)){diagnostics::log(std::string("[UI] non-download link selected: ")+link.url);return;}if(linkAction_(items_[i],link)){state_.linkNavigation=false;state_.linkFocus=-1;}}
void FullCatalogScreen::changeCatalog(int d){int v=(int)state_.catalog+d,c=(int)CatalogType::Count;if(v<0)v=c-1;if(v>=c)v=0;CatalogType next=(CatalogType)v;if(catalogChange_){releaseTextures();if(imageCache_)imageCache_->cancelQueuedRequests();if(catalogChange_(next)){searchQuery_.clear();items_=allItems_;state_.focusIndex=0;state_.catalogScrollRow=0;state_.detailScroll=0;state_.linkFocus=-1;state_.linkNavigation=false;catalogLoading_=true;catalogLoadingLabel_=catalogName(next);catalogLoadingCurrent_=0;catalogLoadingTotal_=0;catalogLoadingMessage_="Checking catalog cache...";catalogError_.clear();}return;}setActiveCatalog(next);}
bool FullCatalogScreen::isTransitioning()const{return state_.mode==UiMode::OPENING_DETAIL||state_.mode==UiMode::CLOSING_DETAIL;}
void FullCatalogScreen::startOpeningDetail(){if(state_.mode!=UiMode::FULL_CATALOG||catalogLoading_||installProgressActive_||selectedIndex()<0)return;state_.detailScroll=0;state_.linkFocus=-1;state_.linkNavigation=false;state_.transitionStart=sceKernelGetProcessTimeWide();state_.mode=UiMode::OPENING_DETAIL;diagnostics::log("[UI] opening detail");}
void FullCatalogScreen::startClosingDetail(){if(state_.mode!=UiMode::SPLIT_DETAIL)return;state_.linkNavigation=false;state_.linkFocus=-1;state_.transitionStart=sceKernelGetProcessTimeWide();state_.mode=UiMode::CLOSING_DETAIL;diagnostics::log("[UI] closing detail");}
float FullCatalogScreen::transitionProgress()const{if(!isTransitioning())return 1.0f;uint64_t e=sceKernelGetProcessTimeWide()-state_.transitionStart;return std::max(0.0f,std::min(1.0f,(float)e/(float)(TRANSITION_MS*1000)));}
void FullCatalogScreen::updateTransition(){if(!isTransitioning()||transitionProgress()<1.0f)return;state_.mode=state_.mode==UiMode::OPENING_DETAIL?UiMode::SPLIT_DETAIL:UiMode::FULL_CATALOG;state_.activePanel=UiPanel::Catalog;clampCatalogScroll();}

void FullCatalogScreen::handleInput(){if(isTransitioning())return;SceCtrlData p{};sceCtrlPeekBufferPositive(0,&p,1);static uint32_t prev=0;static uint64_t repeatAt=0;const uint32_t dpadMask=SCE_CTRL_UP|SCE_CTRL_DOWN|SCE_CTRL_LEFT|SCE_CTRL_RIGHT;const uint32_t pressed=p.buttons&~prev;const uint32_t dpadPressed=pressed&dpadMask;const uint64_t now=sceKernelGetProcessTimeWide();uint32_t dpadRepeat=0;if((p.buttons&dpadMask)==0){repeatAt=0;}else if(dpadPressed!=0){repeatAt=now+DIRECTION_REPEAT_DELAY_US;}else if(repeatAt!=0&&now>=repeatAt){dpadRepeat=p.buttons&dpadMask;repeatAt=now+DIRECTION_REPEAT_INTERVAL_US;}prev=p.buttons;const uint32_t nav=dpadPressed|dpadRepeat;if(pressed&SCE_CTRL_START){state_.requestExit=true;return;}if(pressed&SCE_CTRL_LTRIGGER){changeCatalog(-1);return;}if(pressed&SCE_CTRL_RTRIGGER){changeCatalog(1);return;}if(catalogLoading_||installProgressActive_)return;if(pressed&SCE_CTRL_SQUARE){if(!searchQuery_.empty()){applySearch("");}return;}if(state_.mode==UiMode::FULL_CATALOG){if(pressed&SCE_CTRL_TRIANGLE){if(searchRequest_){const std::string q=searchRequest_(searchQuery_);applySearch(q);}return;}if(nav&SCE_CTRL_LEFT){if(state_.focusIndex%3>0)--state_.focusIndex;}if(nav&SCE_CTRL_RIGHT){if(state_.focusIndex%3<2&&state_.focusIndex+1<(int)items_.size())++state_.focusIndex;}if(nav&SCE_CTRL_UP)moveCatalogFocus(-1);if(nav&SCE_CTRL_DOWN)moveCatalogFocus(1);clampCatalogScroll();if(pressed&SCE_CTRL_CROSS)startOpeningDetail();return;}if(state_.mode!=UiMode::SPLIT_DETAIL)return;if(pressed&SCE_CTRL_CIRCLE){startClosingDetail();return;}if(state_.activePanel==UiPanel::Catalog){if(pressed&SCE_CTRL_RIGHT)state_.activePanel=UiPanel::Detail;if(nav&SCE_CTRL_UP)moveCatalogFocus(-1);if(nav&SCE_CTRL_DOWN)moveCatalogFocus(1);return;}if(nav&SCE_CTRL_LEFT)state_.activePanel=UiPanel::Catalog;if(pressed&SCE_CTRL_TRIANGLE){if(!items_.empty()&&!items_[selectedIndex()].linkDetails.empty()){state_.linkNavigation=!state_.linkNavigation;if(state_.linkNavigation){moveLinkFocus(0,0);}}return;}if(state_.linkNavigation){if(nav&SCE_CTRL_UP)moveLinkFocus(0,-1);if(nav&SCE_CTRL_DOWN)moveLinkFocus(0,1);if(pressed&SCE_CTRL_CROSS)activateFocusedLink();return;}if(nav&SCE_CTRL_UP)moveDetailScroll(-1);if(nav&SCE_CTRL_DOWN)moveDetailScroll(1);if(pressed&SCE_CTRL_CROSS&&!items_.empty()&&!items_[selectedIndex()].linkDetails.empty()){state_.linkNavigation=true;moveLinkFocus(0,0);}}

unsigned FullCatalogScreen::colorForStatus(const std::string&s)const{if(s=="Verified")return ACCENT;if(s=="Legacy")return TEXT;if(s=="Archive")return DIM;return TEXT;}
void FullCatalogScreen::drawHeader(int w){vita2d_draw_rectangle(0,0,w,HEADER_H,SURFACE2);vita2d_pgf_draw_text(font_,16,32,ACCENT,1.12f,"PSVitaAlive Store");vita2d_pgf_draw_text(font_,w-132,32,DIM,.76f,"START: Exit");if(!searchQuery_.empty()){const std::string label="Filter: "+ellipsize(searchQuery_,22);const int approxWidth=(int)label.size()*7;vita2d_pgf_draw_text(font_,std::max(16,(w-approxWidth)/2),32,ACCENT,.66f,label.c_str());}}
void FullCatalogScreen::drawTabs(int w){vita2d_draw_rectangle(0,HEADER_H,w,TABS_H,SURFACE);float tw=(float)w/(int)CatalogType::Count;for(int i=0;i<(int)CatalogType::Count;++i){int x=(int)(i*tw);bool a=(int)state_.catalog==i;if(a)vita2d_draw_rectangle(x,HEADER_H+TABS_H-3,(int)tw,3,ACCENT);vita2d_pgf_draw_text(font_,x+12,HEADER_H+24,a?ACCENT:TEXT,.80f,catalogName((CatalogType)i));}}

void FullCatalogScreen::drawImage(const std::string&url,const std::string&ns,int x,int y,int w,int h){vita2d_draw_rectangle(x,y,w,h,SURFACE2);if(!imageCache_||url.empty())return;std::string path=imageCache_->request(url,ns);if(imageCache_->isFailed(path)||!imageCache_->isReady(path))return;auto it=textures_.find(path);if(it==textures_.end()){evictTextureIfNeeded(ns);vita2d_texture*t=nullptr;const char*e=extOf(path);if(std::strcmp(e,".jpg")==0||std::strcmp(e,".jpeg")==0)t=vita2d_load_JPEG_file(path.c_str());else t=vita2d_load_PNG_file(path.c_str());if(!t){SceIoStat st={};long long size=-1;if(sceIoGetstat(path.c_str(),&st)>=0)size=(long long)st.st_size;char m[700];sceClibSnprintf(m,sizeof(m),"[UI] texture load failed ns=%s path=%s size=%lld",ns.c_str(),path.c_str(),size);diagnostics::log(m);return;}textures_[path]=t;textureOrder_.push_back(path);}else touchTexture(path);vita2d_texture*t=textures_[path];float tw=(float)vita2d_texture_get_width(t),th=(float)vita2d_texture_get_height(t);if(tw<=0||th<=0)return;float s=std::min((float)w/tw,(float)h/th),dw=tw*s,dh=th*s;vita2d_draw_texture_scale(t,x+(w-dw)/2.0f,y+(h-dh)/2.0f,s,s);}

void FullCatalogScreen::drawCatalogCard(const CatalogItem&it,int idx,int x,int y,int w,int h,bool focus){vita2d_draw_rectangle(x,y,w,h,SURFACE);if(focus){vita2d_draw_rectangle(x,y,w,3,ACCENT);vita2d_draw_rectangle(x,y+h-3,w,3,ACCENT);vita2d_draw_rectangle(x,y,3,h,ACCENT);vita2d_draw_rectangle(x+w-3,y,3,h,ACCENT);}else vita2d_draw_rectangle(x,y,w,1,BORDER);int is=h>=100?76:54;drawImage(!it.icon.empty()?it.icon:it.cover,"app",x+10,y+9,is,is);int tx=x+is+20;vita2d_pgf_draw_text(font_,tx,y+25,WHITE,.76f,ellipsize(it.name,h>=100?24:22).c_str());vita2d_pgf_draw_text(font_,tx,y+45,TEXT,.64f,ellipsize(it.author.empty()?"Unknown author":it.author,20).c_str());vita2d_pgf_draw_text(font_,tx,y+64,colorForStatus(it.status),.62f,ellipsize(it.status,16).c_str());std::string meta=(it.version.empty()?"":"v"+it.version)+(it.versionDate.empty()?"":"  "+it.versionDate);if(meta.empty())meta=it.size;if(!meta.empty())vita2d_pgf_draw_text(font_,x+10,y+h-10,DIM,.58f,ellipsize(meta,30).c_str());(void)idx;}
void FullCatalogScreen::drawCatalogPanel(int x,int y,int w,int h,bool split){vita2d_draw_rectangle(x,y,w,h,PANEL);if(!split){const int vis=visibleRowsFull(),rows=totalRows(),cw=(w-GRID_PAD*2-CARD_GAP*2)/3;for(int r=0;r<vis;++r)for(int c=0;c<3;++c){int i=(state_.catalogScrollRow+r)*3+c;if(i<(int)items_.size())drawCatalogCard(items_[i],i,x+GRID_PAD+c*(cw+CARD_GAP),y+GRID_PAD+r*(FULL_CARD_H+CARD_GAP),cw,FULL_CARD_H,i==state_.focusIndex);}if(rows>vis){const int tx=x+w-7,ty=y+10,th=h-20;vita2d_draw_rectangle(tx,ty,3,th,BORDER);const int thumb=std::max(20,th*vis/rows),maxRow=std::max(1,rows-vis),yy=ty+(th-thumb)*state_.catalogScrollRow/maxRow;vita2d_draw_rectangle(tx,yy,3,thumb,ACCENT);}}else for(int r=0;r<visibleRowsSplit();++r){int i=state_.catalogScrollRow+r;if(i<(int)items_.size())drawCatalogCard(items_[i],i,x+GRID_PAD,y+GRID_PAD+r*(SPLIT_CARD_H+CARD_GAP),w-GRID_PAD*2,SPLIT_CARD_H,i==state_.focusIndex);}if(state_.mode==UiMode::SPLIT_DETAIL&&state_.activePanel==UiPanel::Catalog)vita2d_draw_rectangle(x,y,3,h,ACCENT);}

void FullCatalogScreen::wrapText(const std::string&text,int max,std::vector<std::string>&out)const{out.clear();std::string cur;for(char c:text){if(c=='\n'){out.push_back(cur);cur.clear();continue;}if((int)cur.size()>=max&&c==' '){out.push_back(cur);cur.clear();continue;}cur.push_back(c);if((int)cur.size()>=max){out.push_back(cur);cur.clear();}}if(!cur.empty())out.push_back(cur);}
void FullCatalogScreen::drawTextLines(const std::vector<std::string>&l,int x,int y,int lh,unsigned col,float sc,int start,int max,int clipTop,int clipBottom){int first=std::max(0,start),last=std::min((int)l.size(),first+max),dy=y+first*lh;for(int i=first;i<last;++i){if(dy>=clipTop&&dy<=clipBottom)vita2d_pgf_draw_text(font_,x,dy,col,sc,l[i].c_str());dy+=lh;}}

void FullCatalogScreen::drawDetailLinks(const CatalogItem&it,int x,int y,int w,int&heightOut){heightOut=0;if(it.linkDetails.empty())return;for(size_t i=0;i<it.linkDetails.size();++i){const CatalogLink&l=it.linkDetails[i];const bool focused=state_.linkNavigation&&state_.linkFocus==(int)i;const bool can=actionableLink(l);const int rowY=y+(int)i*(LINK_ROW_H+LINK_GAP);vita2d_draw_rectangle(x,rowY,w,LINK_ROW_H,focused?ACCENT:SURFACE2);vita2d_draw_rectangle(x,rowY,w,1,focused?ACCENT:BORDER);const unsigned mainCol=focused?BG:(can?WHITE:TEXT);const std::string title=l.name.empty()?l.type:l.name;const int badgeW=l.recommended?104:0;vita2d_pgf_draw_text(font_,x+10,rowY+15,mainCol,.66f,ellipsize(title,badgeW?24:30).c_str());std::string meta=l.type;if(can)meta+="  • Cross: action";vita2d_pgf_draw_text(font_,x+10,rowY+31,focused?BG:DIM,.52f,ellipsize(meta,badgeW?30:50).c_str());if(l.recommended){const int bx=x+w-badgeW-10,by=rowY+8;vita2d_draw_rectangle(bx,by,badgeW,22,focused?BG:ACCENT);vita2d_pgf_draw_text(font_,bx+8,by+15,focused?ACCENT:BG,.52f,"Recommended");}}heightOut=10+(int)it.linkDetails.size()*(LINK_ROW_H+LINK_GAP);}

void FullCatalogScreen::drawDetailContent(const CatalogItem&it,int x,int y,int w,int h){const int cx=x+18,cw=w-36,maxChars=std::max(18,cw/7),contentTop=y+DETAIL_HEADER_H+10,contentBottom=y+h-10;std::vector<std::string>pre,post;auto add=[&](std::vector<std::string>&lines,const char*t,const std::string&v){if(v.empty())return;lines.push_back(t);std::vector<std::string>q;wrapText(v,maxChars,q);for(auto&s:q)lines.push_back(s);lines.push_back("");};add(pre,"Description",it.description);add(pre,"Long Description",it.longDescription);add(post,"Requirements",it.requirements);post.push_back("Information");post.push_back("Title ID: "+it.titleId);post.push_back("Version: "+it.version);post.push_back("Release date: "+it.versionDate);post.push_back("Category: "+it.category);post.push_back("Subcategory: "+it.subcategory);post.push_back("Size: "+it.size);post.push_back("Status: "+it.status);post.push_back("");add(post,"Changelog",it.changelog);const int screenshotCount=std::min(5,(int)it.screenshots.size()),screenshotRows=(screenshotCount+2)/3,screenshotHeight=screenshotRows*SCREENSHOT_ROW_H;int linksHeight=0;const int scroll=std::max(0,state_.detailScroll);vita2d_enable_clipping();vita2d_set_clip_rectangle(x+2,contentTop,x+w-18,contentBottom);drawDetailLinks(it,cx,contentTop-scroll,cw,linksHeight);const int preTop=contentTop+linksHeight-scroll;drawTextLines(pre,cx,preTop,LINE_H,TEXT,.66f,0,(int)pre.size(),contentTop,contentBottom);const int shotTop=preTop+(int)pre.size()*LINE_H,sw=std::max(70,(cw-16)/3);for(int i=0;i<screenshotCount;++i){int row=i/3,col=i%3;drawImage(it.screenshots[i],"shot",cx+col*(sw+8),shotTop+row*SCREENSHOT_ROW_H,sw,72);}const int postTop=shotTop+screenshotHeight+8;drawTextLines(post,cx,postTop,LINE_H,TEXT,.66f,0,(int)post.size(),contentTop,contentBottom);vita2d_disable_clipping();const int total=detailContentHeight(it,w),visible=std::max(1,h-DETAIL_HEADER_H-18),maxScroll=std::max(0,total-visible);if(maxScroll>0){int tx=x+w-8,ty=y+DETAIL_HEADER_H+8,th=h-DETAIL_HEADER_H-18;vita2d_draw_rectangle(tx,ty,3,th,BORDER);int thumb=std::max(20,th*visible/std::max(1,total)),yy=ty+(th-thumb)*scroll/maxScroll;vita2d_draw_rectangle(tx,yy,3,thumb,ACCENT);}}

void FullCatalogScreen::drawDetailPanel(int x,int y,int w,int h){vita2d_draw_rectangle(x,y,w,h,PANEL);int i=selectedIndex();if(i<0)return;const CatalogItem&it=items_[i];if(state_.activePanel==UiPanel::Detail)vita2d_draw_rectangle(x+w-3,y,3,h,ACCENT);vita2d_draw_rectangle(x,y,w,DETAIL_HEADER_H,SURFACE);drawImage(!it.icon.empty()?it.icon:it.cover,"app",x+12,y+12,68,68);vita2d_pgf_draw_text(font_,x+92,y+29,WHITE,.82f,ellipsize(it.name,24).c_str());vita2d_pgf_draw_text(font_,x+92,y+50,TEXT,.64f,ellipsize(it.author.empty()?"Unknown author":it.author,22).c_str());const std::string meta=(it.version.empty()?"":"v"+it.version)+(it.versionDate.empty()?"":"  "+it.versionDate);vita2d_pgf_draw_text(font_,x+92,y+70,colorForStatus(it.status),.60f,ellipsize(meta.empty()?it.status:meta,25).c_str());if(!it.linkDetails.empty()){const int bx=x+w-142,by=y+12,bw=128,bh=28;vita2d_draw_rectangle(bx,by,bw,bh,state_.linkNavigation?ACCENT:SURFACE2);vita2d_draw_rectangle(bx,by,bw,1,ACCENT);vita2d_draw_rectangle(bx,by,1,bh,ACCENT);vita2d_draw_rectangle(bx,by+bh-1,bw,1,ACCENT);vita2d_draw_rectangle(bx+bw-1,by,1,bh,ACCENT);vita2d_pgf_draw_text(font_,bx+10,by+19,state_.linkNavigation?BG:ACCENT,.56f,state_.linkNavigation?"△ Exit link mode":"△ Select links");}drawDetailContent(it,x,y,w,h);}

void FullCatalogScreen::drawLoadingOverlay(){const bool install=installProgressActive_;int w=620,h=250,x=(SCREEN_W-w)/2,y=(SCREEN_H-h)/2;vita2d_draw_rectangle(0,0,SCREEN_W,SCREEN_H,RGBA8(0,0,0,185));vita2d_draw_rectangle(x,y,w,h,SURFACE2);vita2d_draw_rectangle(x,y,w,2,ACCENT);vita2d_pgf_draw_text(font_,x+28,y+32,ACCENT,.68f,"PSVitaAlive");vita2d_pgf_draw_text(font_,x+28,y+68,WHITE,1.02f,(install?"Installing / Downloading":"Loading "+catalogLoadingLabel_+"...").c_str());if(install){vita2d_pgf_draw_text(font_,x+28,y+94,ACCENT,.72f,installProgressStage_.empty()?"Preparing":installProgressStage_.c_str());vita2d_pgf_draw_text(font_,x+28,y+118,TEXT,.62f,installProgressFile_.empty()?"File":installProgressFile_.c_str());vita2d_pgf_draw_text(font_,x+28,y+142,TEXT,.64f,installProgressMessage_.empty()?"Working...":installProgressMessage_.c_str());int bx=x+28,by=y+160,bw=w-56,bh=12;vita2d_draw_rectangle(bx,by,bw,bh,BORDER);uint32_t pct=installProgressTotal_?(uint32_t)std::min<uint64_t>(100,(installProgressCurrent_*100)/installProgressTotal_):0;vita2d_draw_rectangle(bx,by,bw*pct/100,bh,ACCENT);char p[96];sceClibSnprintf(p,sizeof(p),"%u%%   %s / %s",pct,formatBytes(installProgressCurrent_).c_str(),installProgressTotal_?formatBytes(installProgressTotal_).c_str():"?");vita2d_pgf_draw_text(font_,x+28,y+194,TEXT,.66f,p);char s[64];sceClibSnprintf(s,sizeof(s),"Speed: %s/s",formatBytes(installProgressSpeed_).c_str());vita2d_pgf_draw_text(font_,x+w-190,y+194,DIM,.60f,s);}else{vita2d_pgf_draw_text(font_,x+28,y+100,TEXT,.68f,catalogLoadingMessage_.c_str());int bx=x+28,by=y+132,bw=w-56,bh=12;vita2d_draw_rectangle(bx,by,bw,bh,BORDER);uint32_t pct=catalogLoadingTotal_?(uint32_t)std::min<uint64_t>(100,(catalogLoadingCurrent_*100)/catalogLoadingTotal_):20;vita2d_draw_rectangle(bx,by,bw*pct/100,bh,ACCENT);char p[24];sceClibSnprintf(p,sizeof(p),"%u%%",pct);vita2d_pgf_draw_text(font_,x+28,y+176,TEXT,.74f,p);}}

void FullCatalogScreen::drawFullCatalog(){vita2d_start_drawing();vita2d_clear_screen();drawHeader(SCREEN_W);drawTabs(SCREEN_W);drawCatalogPanel(0,HEADER_H+TABS_H,SCREEN_W,SCREEN_H-HEADER_H-TABS_H-FOOTER_H,false);vita2d_draw_rectangle(0,SCREEN_H-FOOTER_H,SCREEN_W,FOOTER_H,SURFACE2);vita2d_pgf_draw_text(font_,12,SCREEN_H-14,TEXT,.58f,"D-Pad: Navigate   X: Detail   △: Search   □: Clear Filter   L/R: Catalog   START: Exit");if(catalogLoading_||installProgressActive_)drawLoadingOverlay();if(!catalogError_.empty())vita2d_pgf_draw_text(font_,18,HEADER_H+TABS_H+26,ACCENT,.68f,catalogError_.c_str());vita2d_end_drawing();vita2d_swap_buffers();}
void FullCatalogScreen::drawSplitDetail(){vita2d_start_drawing();vita2d_clear_screen();drawHeader(SCREEN_W);drawTabs(SCREEN_W);int top=HEADER_H+TABS_H,hh=SCREEN_H-HEADER_H-TABS_H-FOOTER_H,lw=SCREEN_W/2;drawCatalogPanel(0,top,lw,hh,true);drawDetailPanel(lw,top,SCREEN_W-lw,hh);vita2d_draw_rectangle(lw-1,top,2,hh,BORDER);vita2d_draw_rectangle(0,SCREEN_H-FOOTER_H,SCREEN_W,FOOTER_H,SURFACE2);vita2d_pgf_draw_text(font_,12,SCREEN_H-14,TEXT,.56f,"D-Pad: Navigate/Scroll   X: Select Link   △: Link Mode   □: Clear Filter   O: Back   L/R: Catalog");if(catalogLoading_||installProgressActive_)drawLoadingOverlay();vita2d_end_drawing();vita2d_swap_buffers();}
void FullCatalogScreen::drawOpeningDetail(){float p=transitionProgress();int lw=SCREEN_W-(int)(SCREEN_W/2*p),rw=SCREEN_W-lw;vita2d_start_drawing();vita2d_clear_screen();drawHeader(SCREEN_W);drawTabs(SCREEN_W);int top=HEADER_H+TABS_H,hh=SCREEN_H-HEADER_H-TABS_H-FOOTER_H;drawCatalogPanel(0,top,lw,hh,true);if(rw>0)drawDetailPanel(lw,top,rw,hh);vita2d_end_drawing();vita2d_swap_buffers();}
void FullCatalogScreen::drawClosingDetail(){float p=1.0f-transitionProgress();int lw=SCREEN_W-(int)(SCREEN_W/2*p),rw=SCREEN_W-lw;vita2d_start_drawing();vita2d_clear_screen();drawHeader(SCREEN_W);drawTabs(SCREEN_W);int top=HEADER_H+TABS_H,hh=SCREEN_H-HEADER_H-TABS_H-FOOTER_H;drawCatalogPanel(0,top,lw,hh,true);if(rw>0)drawDetailPanel(lw,top,rw,hh);vita2d_end_drawing();vita2d_swap_buffers();}
void FullCatalogScreen::draw(){switch(state_.mode){case UiMode::FULL_CATALOG:drawFullCatalog();break;case UiMode::OPENING_DETAIL:drawOpeningDetail();break;case UiMode::SPLIT_DETAIL:drawSplitDetail();break;case UiMode::CLOSING_DETAIL:drawClosingDetail();break;}}
bool FullCatalogScreen::updateAndDraw(){if(!ready_)return false;handleInput();updateTransition();draw();return !state_.requestExit;}

} // namespace psvitaalive::ui
